@MultiTanentInvetory_HostAddress = http://localhost:5020

GET {{MultiTanentInvetory_HostAddress}}/api/items
Accept: application/json
X-Tenant-ID: alpha-logistics

###

GET {{MultiTanentInvetory_HostAddress}}/debug/data
Accept: application/json
X-Tenant-ID: alpha-logistics

###

POST {{MultiTanentInvetory_HostAddress}}/api/items
Content-Type: application/json
Accept: application/json
X-Tenant-ID: alpha-logistics

{
  "name": "a",
  "category": "Electronics",
  "description": "a nice and very important"
}

###

POST {{MultiTanentInvetory_HostAddress}}/api/items/9/checkout
Content-Type: application/json
Accept: application/json
X-Tenant-ID: alpha-logistics

{
  "userId": "user123"
}

###

POST {{MultiTanentInvetory_HostAddress}}/api/items/2/checkin
Content-Type: application/json
Accept: application/json
X-Tenant-ID: alpha-logistics

{
  "itemId": 2
}


###

DELETE {{MultiTanentInvetory_HostAddress}}/api/items/3
Accept: application/json
X-Tenant-ID: alpha-logistics


###

POST {{MultiTanentInvetory_HostAddress}}/api/tenant/
Content-Type: application/json
Accept: application/json
{
  "id": 2,
  "name" : "beta-supply"
}

###

GET {{MultiTanentInvetory_HostAddress}}/api/tenant/
Accept: application/json
X-Tenant-ID: alpha-logistics

